# Generated by Django 3.2.6 on 2021-08-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_contactm_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_web_site', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Доменное имя данного сайта',
                'verbose_name_plural': 'Доменные имена данного сайта',
            },
        ),
    ]
