# Generated by Django 3.2.6 on 2021-08-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_website'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactnumber',
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Заявки на Безпплатную Консультацию', 'verbose_name_plural': 'Заявки на Безпплатныи  Консультации'},
        ),
        migrations.AlterField(
            model_name='website',
            name='name_web_site',
            field=models.CharField(max_length=100, verbose_name='Введите Доменное имя данного сайта'),
        ),
    ]
