# Generated by Django 3.2.5 on 2021-07-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesdescription',
            options={'verbose_name': 'Создание-Редактирование услуг', 'verbose_name_plural': 'Создание-Редактирование услуг'},
        ),
        migrations.RenameField(
            model_name='servicesdescription',
            old_name='text',
            new_name='content',
        ),
    ]
