# Generated by Django 3.2.5 on 2021-07-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210723_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesdescription',
            name='content',
            field=models.TextField(verbose_name='Описание услуги'),
        ),
        migrations.AlterField(
            model_name='servicesdescription',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название услуги'),
        ),
    ]
