# Generated by Django 3.2.5 on 2021-07-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210723_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_email', models.CharField(max_length=30, verbose_name='Введите Email')),
            ],
            options={
                'verbose_name': 'Настройка Email в футере',
                'verbose_name_plural': 'Настройка Email в футере',
            },
        ),
        migrations.CreateModel(
            name='FooterNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Введите номер телефона')),
            ],
            options={
                'verbose_name': 'Настройка номеров в Футере',
                'verbose_name_plural': 'Настройка номера в Футере',
            },
        ),
        migrations.CreateModel(
            name='HaveQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='Введите Адрес организации')),
            ],
            options={
                'verbose_name': 'Настройка Адресов',
                'verbose_name_plural': 'Настройка Адреса',
            },
        ),
        migrations.CreateModel(
            name='VkLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_vk_link', models.CharField(max_length=150, verbose_name='Введите ссылку на "VK" включая "http://...."')),
                ('name_vk', models.CharField(max_length=30, verbose_name='Назовите ссылку, так она будет отображаться на сайте:')),
            ],
            options={
                'verbose_name': 'Настройка ссылки на "VK" в футере',
                'verbose_name_plural': 'Настройка ссылки на "VK" в футере',
            },
        ),
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_adm', models.CharField(default='Рабочие дни и часы в неделе', max_length=35, verbose_name='Имя для отображения в админке, можно не менят)')),
                ('work_days_1', models.CharField(default='Понедельник - пятница:', max_length=35, verbose_name='Рабочии дни с Пн по Пт')),
                ('work_tim_1', models.CharField(default='с 10:00 до 18:00', max_length=35, verbose_name='Напишите рабочии часы, менять только цыфры')),
                ('work_days_2', models.CharField(default='Суббота:', max_length=35, verbose_name='Рабочии дни в Сб - Вс')),
                ('work_time_2', models.CharField(default='с 10:00 до 15:00', max_length=35, verbose_name='Напишите рабочии часы, менять только цыфры')),
                ('week_days', models.CharField(default='Все воскресные дни.', max_length=35, verbose_name='Какие дни выходные?')),
                ('holidays', models.CharField(default='Все официальные праздники.', max_length=35, verbose_name='Выхдные в какие праздники?')),
            ],
            options={
                'verbose_name': 'Настройка Рабочих дней и часов в неделе',
                'verbose_name_plural': 'Настройка Рабочих дней и часов в неделе',
            },
        ),
    ]
