# Generated by Django 3.2.5 on 2021-08-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_lawyercard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='FooterNumber',
        ),
        migrations.DeleteModel(
            name='HaveQuestions',
        ),
        migrations.DeleteModel(
            name='LawyerCard',
        ),
        migrations.DeleteModel(
            name='VkLink',
        ),
        migrations.DeleteModel(
            name='WorkHours',
        ),
    ]
