# Generated by Django 3.2.5 on 2021-07-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfoBoxTop',
            new_name='Infobox',
        ),
    ]
