# Generated by Django 3.2.5 on 2021-07-22 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_infoboxtop_infobox'),
    ]

    operations = [
        migrations.AddField(
            model_name='infobox',
            name='icon',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
