# Generated by Django 3.2.5 on 2021-07-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_practiceareas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PracticeAreas',
        ),
    ]
