# Generated by Django 3.2.5 on 2021-07-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_practiceareas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infobox',
            options={'verbose_name': 'Настройки верхнего блока', 'verbose_name_plural': 'Настройки верхнего блока'},
        ),
    ]
