# Generated by Django 3.2.5 on 2021-07-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_infobox_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Настройки блока достижения',
                'verbose_name_plural': 'Настройки блока достижения',
            },
        ),
    ]
