# Generated by Django 3.2.5 on 2021-07-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210723_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=30, verbose_name='Иконка блока')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок блока')),
                ('createid', models.CharField(max_length=25, verbose_name='Присвой id блоку в виде строки')),
            ],
            options={
                'verbose_name': 'Настройка блока Области практики',
                'verbose_name_plural': 'Настройка блока Области практики',
            },
        ),
        migrations.AlterModelOptions(
            name='uploadvideo',
            options={'verbose_name': 'Загрузка видео на главную', 'verbose_name_plural': 'Загрузка видео на главную'},
        ),
        migrations.AlterField(
            model_name='uploadvideo',
            name='name',
            field=models.CharField(default='Видео на главной', max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='uploadvideo',
            name='preview',
            field=models.ImageField(upload_to='videoimage', verbose_name='Превью для видео'),
        ),
        migrations.AlterField(
            model_name='uploadvideo',
            name='video',
            field=models.FileField(upload_to='videoimage', verbose_name='Выбери видео'),
        ),
    ]
