# Generated by Django 3.2.5 on 2021-07-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210723_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя, Фамилия - юриста')),
                ('lawyer_classification', models.CharField(max_length=30, verbose_name='В какой области практикует юрист?')),
                ('image', models.ImageField(upload_to='lawyerimage', verbose_name='Фото в карточке юриста')),
                ('text', models.TextField(max_length=190, verbose_name='Текст с зади карточки 190-символов')),
            ],
            options={
                'verbose_name': 'Настройка карточки юриста',
                'verbose_name_plural': 'Настройка карточек юриста',
            },
        ),
    ]
