# Generated by Django 3.2.5 on 2021-07-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_lawyercard'),
    ]

    operations = [
        migrations.CreateModel(
            name='VashePravoImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=30, verbose_name='Иконка блока')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок блока')),
                ('text', models.CharField(max_length=25, verbose_name='Содержание блока')),
                ('image', models.ImageField(upload_to='vpimages', verbose_name='Картинка на фон блока')),
            ],
            options={
                'verbose_name': 'Настройка блока слева от формы.беспл.конс:',
                'verbose_name_plural': 'Настройка блока слева от формы.беспл.конс:',
            },
        ),
    ]
