# Generated by Django 3.2.5 on 2021-07-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_vashepravoimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='revievsimages', verbose_name='Фото написавшего отзыв')),
                ('text', models.CharField(max_length=120, verbose_name='Текст отзыва')),
                ('name', models.CharField(max_length=20, verbose_name='Имя писавшего отзыв')),
            ],
            options={
                'verbose_name': 'Написание отзывов от клиента',
                'verbose_name_plural': 'Написание отзывов от клиентов',
            },
        ),
    ]
