# Generated by Django 3.2.5 on 2021-07-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210723_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(default=1, max_length=20, verbose_name='Имя фото для отображения в Админке'),
            preserve_default=False,
        ),
    ]
