# Generated by Django 3.2.5 on 2021-07-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_gallery_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Введите номер телефона')),
            ],
            options={
                'verbose_name': 'Настройка номеров в Футере',
                'verbose_name_plural': 'Настройка номера в Футере',
            },
        ),
    ]
