# Generated by Django 3.2.5 on 2021-07-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_email_vklink_workhours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhours',
            name='holidays',
            field=models.CharField(default='Все официальные праздники.', max_length=35, verbose_name='Выхдные в какие праздники?'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='name_adm',
            field=models.CharField(default='Рабочие дни и часы в неделе', max_length=35, verbose_name='Имя для отображения в админке, можно не менят)'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='week_days',
            field=models.CharField(default='Все воскресные дни.', max_length=35, verbose_name='Какие дни выходные?'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='work_days_1',
            field=models.CharField(default='Понедельник - пятница:', max_length=35, verbose_name='Рабочии дни с Пн по Пт'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='work_days_2',
            field=models.CharField(default='Суббота:', max_length=35, verbose_name='Рабочии дни в Сб - Вс'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='work_tim_1',
            field=models.CharField(default='с 10:00 до 18:00', max_length=35, verbose_name='Напишите рабочии часы, менять только цыфры'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='work_time_2',
            field=models.CharField(default='с 10:00 до 15:00', max_length=35, verbose_name='Напишите рабочии часы, менять только цыфры'),
        ),
    ]
