# Generated by Django 3.2.5 on 2021-07-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210724_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaveQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='Введите Адрес организации')),
            ],
            options={
                'verbose_name': 'Настройка Адресов',
                'verbose_name_plural': 'Настройка Адреса',
            },
        ),
    ]
