# Generated by Django 3.2.6 on 2021-08-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_havequestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceareas',
            name='createid',
            field=models.CharField(max_length=25, verbose_name='Присвой id блоку числом от 1 до ...'),
        ),
    ]
